-- 1. Create Carts Table
CREATE TABLE carts (
  id bigint generated by default as identity primary key,
  user_email text not null,
  product_id bigint references products(id) on delete cascade,
  quantity integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_email, product_id)
);

-- 2. Disable Row Level Security (RLS) for testing
ALTER TABLE carts DISABLE ROW LEVEL SECURITY;

-- 3. Reload schema cache for PostgREST
NOTIFY pgrst, 'reload schema';
