-- 1. Create Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Disable Row Level Security (RLS) for testing
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;

-- 3. Reload schema cache for PostgREST
NOTIFY pgrst, 'reload schema';
