-- ==========================================
-- FINAL COMPLETE SQL SETUP FOR SHOPIEE
-- Run this ENTIRE block in Supabase SQL Editor
-- ==========================================

-- 1. DROP EXISTING TABLES (To start fresh and avoid conflicts)
-- WARNING: This deletes all existing data. Only run this for setup/fix.
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS wishlists;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;

-- 2. CREATE USERS TABLE (With Email, Password, Mobile)
CREATE TABLE users ( 
  id bigint generated by default as identity primary key,
  email text unique,
  password text,
  mobile_number text unique,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. CREATE PRODUCTS TABLE
CREATE TABLE products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  category text,
  description text,
  image text
);

-- 4. CREATE ORDERS TABLE
CREATE TABLE orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  email text,
  mobile text,
  address text,
  total_amount numeric,
  payment_method text,
  items jsonb,
  status text default 'Processing',
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. CREATE REVIEWS TABLE
CREATE TABLE reviews (
  id bigint generated by default as identity primary key,
  product_id bigint references products(id) on delete cascade,
  user_email text,
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. CREATE WISHLISTS TABLE
CREATE TABLE wishlists (
  id bigint generated by default as identity primary key,
  user_email text,
  product_id bigint references products(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_email, product_id)
);

-- 7. CREATE CARTS TABLE
CREATE TABLE carts (
  id bigint generated by default as identity primary key,
  user_email text not null,
  product_id bigint references products(id) on delete cascade,
  quantity integer default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_email, product_id)
);

-- 8. CREATE CONTACTS TABLE
CREATE TABLE contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 9. DISABLE PERMISSIONS (Fix Registration & Access Errors in local dev)
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE wishlists DISABLE ROW LEVEL SECURITY;
ALTER TABLE carts DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;

-- 10. INSERT SAMPLE PRODUCTS (Amazon Style)
INSERT INTO products (name, price, category, description, image)
VALUES 
('Sony WH-1000XM5 Wireless Headphones', 29990, 'Electronics', 'Industry leading noise cancellation, 30-hour battery life, and superior call quality. Perfect for travel or office work.', 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800&q=80'),
('Apple Watch Series 9', 41900, 'Electronics', 'Advanced health tracking, brighter display, and crack-resistant crystal. Includes ECG and Blood Oxygen apps.', 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=800&q=80'),
('Nike Air Max 2024 Men''s Running Shoes', 12495, 'Fashion', 'Max Air cushioning, breathable mesh upper, and durable rubber outsole for maximum performance and style.', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80'),
('Levi''s Classic Denim Jacket', 4500, 'Fashion', 'Timeless denim jacket with a regular fit and button closures. Made with premium quality cotton.', 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&q=80'),
('Fossil Gen 6 Smartwatch', 23995, 'Accessories', 'Stainless steel touchscreen smartwatch with heart rate, GPS, contactless payments, and smartphone notifications.', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=80'),
('Dell XPS 13 Laptop', 135000, 'Computers', '13.4" FHD+ display, Intel Core i7 12th Gen, 16GB RAM, 512GB SSD. Ultra-thin, light, and powerful.', 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80'),
('Samsung Galaxy S24 Ultra', 129999, 'Mobiles', 'Epical camera system, built-in S-Pen, and Snapdragon 8 Gen 3 processor. The ultimate productivity machine.', 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&q=80'),
('Kindle Paperwhite (11th Gen)', 13999, 'Electronics', 'Now with a 6.8" display and thinner borders, adjustable warm light, up to 10 weeks of battery life, and 20% faster page turns.', 'https://images.unsplash.com/photo-1592496001020-d31bd830651f?w=800&q=80'),
('Bose SoundLink Micro Bluetooth Speaker', 8990, 'Electronics', 'Small portable speaker, waterproof (IP67), tear-resistant strap, robust design. Up to 6 hours play time.', 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80'),
('Herschel Little America Backpack', 9500, 'Accessories', 'Classic mountaineering style, elevated function. Padded and fleece lined 15" laptop sleeve, internal media pocket.', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80'),
('Logitech MX Master 3S Wireless Mouse', 8495, 'Electronics', 'Ergonomic mouse with ultra-fast scrolling, 8K DPI tracking on any surface, and quiet clicks.', 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80'),
('Ray-Ban Classic Aviator Sunglasses', 7500, 'Fashion', 'Iconic aviator sunglasses with gold frame and green classic G-15 lenses. 100% UV protection.', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80'),
('Nespresso Vertuo Next Coffee Machine', 16999, 'Kitchen', 'Brews a wide range of coffees at the touch of a button. Slim fit design, made from 54% recycled plastics.', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80'),
('Apple iPad Air (5th Gen)', 54900, 'Computers', '10.9-inch Liquid Retina display, breakthrough Apple M1 chip, and 12MP Ultra Wide front camera with Center Stage.', 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80'),
('Dyson V15 Detect Vacuum Cleaner', 64900, 'Home', 'Reveals microscopic dust. Automatically adapts suction power. Scientific proof of a deep clean.', 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80');

-- 11. INSERT SAMPLE REVIEWS
INSERT INTO reviews (product_id, user_email, rating, comment)
VALUES
(1, 'demo@test.com', 5, 'Amazing sound quality and the noise cancellation is unreal! Totally worth the price.'),
(1, 'user2@test.com', 4, 'Very comfortable but battery could be slightly better.'),
(2, 'guest@test.com', 5, 'Best smartwatch out there. The new display is super bright.');

-- 12. RELOAD SCHEMA CACHE
NOTIFY pgrst, 'reload schema';
