-- COPY AND RUN THESE QUERIES IN SUPABASE SQL EDITOR --

-- 1. Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null,
  category text,
  description text,
  image text
);

-- 2. Create Users Table
create table users (
  id bigint generated by default as identity primary key,
  mobile_number text unique,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Create Orders Table
create table orders (
  id bigint generated by default as identity primary key,
  customer_name text,
  mobile text,
  address text,
  total_amount numeric,
  payment_method text,
  items jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Insert Initial Mock Data
insert into products (name, price, category, description, image)
values 
('Wireless Headphones', 2999, 'Electronics', 'Premium noise-cancelling wireless headphones with 20h battery life.', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60'),
('Smart Watch Series 5', 4500, 'Electronics', 'Track your fitness and notifications with this sleek smart watch.', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop&q=60'),
('Running Shoes', 1200, 'Fashion', 'Lightweight and breathable running shoes for daily workouts.', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=60'),
('Cotton T-Shirt', 499, 'Fashion', '100% organic cotton t-shirt with a comfortable fit.', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop&q=60'),
('Leather Wallet', 899, 'Accessories', 'Genuine leather wallet with multiple card slots.', 'https://images.unsplash.com/photo-1627123424574-1800390cab1d?w=500&auto=format&fit=crop&q=60'),
('Backpack', 1599, 'Accessories', 'Durable backpack suitable for school, work, or travel.', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&auto=format&fit=crop&q=60');
